#!/bin/bash
killall sslsplit; killall python; killall hostapd
/sbin/iptables --policy INPUT ACCEPT
/sbin/iptables --policy FORWARD ACCEPT
/sbin/iptables --policy OUTPUT ACCEPT
/sbin/iptables -t nat -F
