#!/bin/bash
# Check if first run has already been set up.
configfile=/root/.firstrun.option
# Check to see if firstrun has been run already
if [ -e "$configfile" ]; then
	source $configfile	
	if [ "$FIRSTRUN" == "1" ]; then
		exit
	fi
fi
touch $configfile
#
# BEGIN THE START UP OPTIONS
#
echo ""
echo "Welcome to Kali Linux for Android!"
echo ""
echo "This script will assist with setting up Kali on your Android Device"
echo ""
read -p "Would you like to continue with setup? (y/n): " continue_on
if [ "$continue_on" == "n" ]; then
	clear
	echo "You can visit the settings in kalimenu to change startup settings."
	echo "FIRSTRUN=1" >> $configfile
	exit
fi
# TIME ZONE
read -p "Would you like to set your timezone? (y/n): " timezone
if [ "$timezone" == "y" ]; then
	dpkg-reconfigure tzdata;
fi
# SSH KEYS
clear
read -p "Would you like to generate SSH keys? (y/n): " sshkeys
if [ "$sshkeys" == "y" ]; then
	echo "Generating new keys and removing old ones."
	sleep 3
	rm -rf ~/.ssh/*
	sleep 3
	ssh-keygen -t rsa
	chmod 600 /root/.ssh/id_rsa
	chmod 644 /root/.ssh/id_rsa.pub
	echo "Finished!"
	sleep 2
fi
clear
# SSH STARTUP
read -p "Would you like to start SSH server on boot? (y/n): " sshonboot
if [ "$sshonboot" == "y" ]; then
	echo "sshonboot=1" > $configfile
else
	echo "sshonboot=0" > $configfile
fi
# CONFIG SSH
clear
read -p "Configure the default SSH server? (y/n): " configssh
if [ "$configssh" == "y" ]; then
	#LOCAL OR ALL
	clear
	read -p "Enable password based SSH login? (y/n): " SSHPASS
	if [ "$SSHPASS" == "y" ]; then
		sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
	else
		if [ -e "/root/.ssh/id_rsa" ]; then
		read -p "SSH private key detected.  Would you like to copy private key to SDCARD? (y/n): " SSHKEYCOPY
		fi
	fi
	if [ "$SSHKEYCOPY" == "y" ]; then
		mkdir -p /sdcard/ssh-keys
		cp /root/.ssh/id_rsa /sdcard/ssh-keys/id_rsa
		echo "Copied SSH key to /sdcard/ssh-keys/id_rsa"
		sleep 5
	fi
	#PORT
	read -p "Enter custom SSH server port (default is 22): " -e -i "22" SSHPORT
	sed -i "s/Port .*/Port ${SSHPORT}/g" /etc/ssh/sshd_config
fi
# VNC STARTUP
clear
read -p "Would you like to start a VNC server on boot? (y/n): " vnconboot
if [ "$vnconboot" == "y" ]; then
	echo "vnconboot=1" >> $configfile
else
	echo "vnconboot=0" >> $configfile
fi
# CONFIG VNC RESOLUTION
clear
read -p "Configure VNC server? (y/n): " configvncres
if [ "$configvncres" == "y" ]; then
	clear
	echo "Create a VNC password (between six and eight characters): "
	echo ""
	vncpasswd
	clear
	echo "Choose a default VNC server display resolution:"
	echo ""
	echo "[1] Nexus 7 (2012) - 1280x1024"
	echo "[2] Nexus 7 (2013) - 1920x1200"
	echo "[3] Nexus 10 - 2650x1600"
	echo "[4] Custom Display Size (Computer Monitor)"
	echo ""
	echo -n "Enter your menu choice [1-4]: "
	read -p "Choice:" vncmenu
	case $vncmenu in
	1) echo "RES=1280x1024" >> $configfile ;;
	2) echo "RES=1920x1200" >> $configfile ;;
	3) echo "RES=2560x1600" >> $configfile ;;
	4) f_custom_vnc ;;
	*) echo "Incorrect choice..." ;
	esac

	echo "VNC Server listen on localhost or all interfaces:"
	echo "[1] localhost only - Connect to VNC through Android device or SSH only (most secure)"
	echo "[2] All Interfaces - Device will show up across network (least secure)"
	echo ""
	read -p "Choice:" vnclistenchoice

	case $vnclistenchoice in
	1) echo 'VNCLISTEN="-localhost -nolisten tcp"' >> $configfile ;;
	2) echo "VNCLISTEN=" >> $configfile ;;
	*) echo "Incorrect choice..." ;
	esac
	# CONFIG VNC LISTEN
	f_customvnc(){
		read -p "Enter Custom Display Size (e.g. ####x####) " CUSTOMVNCSIZE
		echo "RES=${CUSTOMVNCSIZE}" >> $configfile
	}
fi
# SETUP METASPLOIT

##############################################################
echo "FIRSTRUN=1" >> $configfile
echo "Initial Setup Complete!"
echo "You can alter settings by launching Kali menu"
